def add_even_fibonaccis():
	count = 2
	temp1 = 1
	temp2 = 2
	temp3 = 0
	while temp3 < 4000000:
		temp3 = temp1+temp2
		temp1 = temp2
		temp2 = temp3
		if temp3 %2 == 0 and temp3<4000000:
			count+= temp3
	print count
	return count
add_even_fibonaccis()

#started+completed in August 2015
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
